# Redirect HTTP to 
# This block handles insecure traffic on port 80 and moves it to a secure connection.
server {

    # The server listens for traffic on Port 80 (the standard "front door" for the web)
    listen 80;

    # This server will respond to any web address (domain) directed to its IP
    server_name kyc.pokerpad.net;

    # 301 Redirect: Tells the browser to permanently move to the HTTPS version.
    # $request_uri ensures that if someone visits support.pokerpad.net/dashboard,
    # they are sent exactly to https://support.pokerpad.net/dashboard.
    return 301 https://kyc.pokerpad.net$request_uri;
}

# Serve main site
# This block handles the actual encrypted traffic and serves the app files.
server {
    # Listen on Port 443
    listen 443 ssl;
    server_name kyc.pokerpad.net;

    # ssl certificate and key
    ssl_certificate /etc/ssl/certs/kyc_pokerpad_net_chain.crt;
    ssl_certificate_key /etc/ssl/private/kyc_pokerpad_net.key;

    # Security Protocols
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # The directory inside the Docker container where your compiled Angular files live
    root /usr/share/nginx/html;

    # The default file to load when a user visits the root domain
    index index.html;

    # --- Angular Routing Support ---
    location / {
        try_files $uri $uri/ /index.html;
    }
}
